// Project Euler, Problem 1
// A solution in Bespoke

// Problem statement:
// If we list all the natural numbers below 10 that are multiples of 3 or 5, 
// we get 3, 5, 6 and 9. The sum of these multiples is 23.

// Find the sum of all the multiples of 3 or 5 below 1000.

for all values of the number x between 1 and 1000
	if the number x is divisible by 3 and the number x is divisible by 5 then
		add the number x to the number sum
		and print the number x

afterwards, print the number sum
